<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BLOG | <?= $article['titre'] ?> </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <?php include('./php-include/nav.phtml'); ?>
    <div class="container-fluid">
        <h2><?= $article['titre'] ?></h2>
        <?php if($article['image'] != NULL):?>
            <img src="./img/<?= $article['image'] ?>">
        <?php endif?>
        <br><br>
        <p><?= $article['contenu'] ?></p>
        <p>Rédiger par <a href="redacteur-article.php?id=<?= intval($article['idRedacteurs']) ?>"><?= $article['pseudo'] ?></a> le <?= date('d-m-Y à G:i', strtotime($article['dateParution'])) ?></p>
    </div>
    <div class="container-fluid">
        <h3>Commentaires : </h3>
        <?php foreach($commentaires as $commentaires):?>
            <article>
                <p><?= $commentaires['pseudoAuteur'] . " : " . $commentaires['contenu'] ?></p>
            </article>
        <?php endforeach ?>
    </div>
    <div class="container-fluid">
        <form action="commentaire.php" method="post">
            <div class="form-group">
                <input type="text" name="pseudoAuteur" placeholder="Pseudo"/>
            </div>
            <input type="hidden" name="idPost" placeholder="Pseudo" value="<?= intval($article['id']) ?>"/>
            <div class="form-group">
                <textarea name="contenu" placeholder="Commentaire..."></textarea>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Publier</button>
        </form>
    </div>
</body>
</html>