    <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="../index.php">Accueil</a>
                        </li>
                        <?php if(array_key_exists('authentification', $_SESSION)): ?>
                            <li class="nav-item">
                                <a class="nav-link" href="../dashboard.php">Mon compte</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="../logout.php">Deconnexion</a>
                            </li>
                        <?php else : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="../sign-up.php">Inscription</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="../sign-in.php">Connexion</a>
                            </li>
                        <?php endif ?>
                    </ul>
                </div>
            </nav>
    </header>