<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>BLOG | Inscription</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	</head>
	<body>
    <?php include('./php-include/nav.phtml'); ?>
        <div class="container-fluid">
            <h1>Inscription</h1>
            <form action="sign-up.php" method="post">
                <div class="form-group">
                    <input type="text" name="pseudo" placeholder="Pseudo"/>
                </div>
                <div class="form-group">
                    <input type="password" name="password" placeholder="Mot de passe"/>
                </div>
                <button type="submit" class="btn btn-primary">S'inscrire</button>
                <p class="message">Vous avez un compte ? <a href="../sign-in.php">Connectez-vous</a></p>
            </form>
            <?php if(isset($erreur)): ?><p class="erreur"><?= $erreur ?></p><?php endif?>
        </div>
	</body>
</html>